name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5

    - run: uv sync

    - name: pytest
      run: uv run pytest
    - name: ruff
      run: uv run ruff check
    - name: check uv.lock
      run: |
        uv sync
        git diff --exit-code uv.lock
